### ISSUE TITLE
come-ti-consideri-come-sviluppatore-php

### ISSUE THREAD

**Issue by simodima** [toretto460/pugroma-questionario#3]
@marco-loche  la domanda https://github.com/toretto460/pugroma-questionario/blob/master/sondaggio.md#come-ti-consideri-come-sviluppatore-php mi sembra un po generica. Come possiamo renderla più chiara?

**Comment by marco-loche** [comment]
Lo scopo era di ottenere risposte del tipo "principiante", "intermedio" o "esperto". Diventa forse irrilevante visto che la domanda successiva è più precisa.
Potremmo benissimo sopprimerla.

**Comment by simodima** [comment]
Allora possiamo toglierla
